// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqkirciomqdagbnrwcfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxa2lyY2lvbXFkYWdibnJ3Y2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTYwNDYsImV4cCI6MjA3MTA5MjA0Nn0.sBJs54Ce9i--YMZukaEUUfsjZYU9pQhlikQy7CsEH70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});